<<<<<<< HEAD
package com.vdc.tv.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.vdc.tv.core.presentation.theme.ColorDark
import com.vdc.tv.core.presentation.theme.ColorLight
import com.vdc.tv.core.presentation.theme.ColorPinkDark
import com.vdc.tv.core.presentation.theme.ColorPinkLight
import com.vdc.tv.core.presentation.theme.ColorPurpleDark
import com.vdc.tv.core.presentation.theme.ColorPurpleLight
=======
package dev.jdtech.jellyfin.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import dev.jdtech.jellyfin.core.presentation.theme.ColorDark
import dev.jdtech.jellyfin.core.presentation.theme.ColorLight
import dev.jdtech.jellyfin.core.presentation.theme.ColorPinkDark
import dev.jdtech.jellyfin.core.presentation.theme.ColorPinkLight
import dev.jdtech.jellyfin.core.presentation.theme.ColorPurpleDark
import dev.jdtech.jellyfin.core.presentation.theme.ColorPurpleLight
>>>>>>> b69d89e43a3035044e06a8a08f11960b3b6083e8

val lightScheme =
    lightColorScheme(
        primary = ColorLight.primaryLight,
        onPrimary = ColorLight.onPrimaryLight,
        primaryContainer = ColorLight.primaryContainerLight,
        onPrimaryContainer = ColorLight.onPrimaryContainerLight,
        secondary = ColorLight.secondaryLight,
        onSecondary = ColorLight.onSecondaryLight,
        secondaryContainer = ColorLight.secondaryContainerLight,
        onSecondaryContainer = ColorLight.onSecondaryContainerLight,
        tertiary = ColorLight.tertiaryLight,
        onTertiary = ColorLight.onTertiaryLight,
        tertiaryContainer = ColorLight.tertiaryContainerLight,
        onTertiaryContainer = ColorLight.onTertiaryContainerLight,
        error = ColorLight.errorLight,
        onError = ColorLight.onErrorLight,
        errorContainer = ColorLight.errorContainerLight,
        onErrorContainer = ColorLight.onErrorContainerLight,
        background = ColorLight.backgroundLight,
        onBackground = ColorLight.onBackgroundLight,
        surface = ColorLight.surfaceLight,
        onSurface = ColorLight.onSurfaceLight,
        surfaceVariant = ColorLight.surfaceVariantLight,
        onSurfaceVariant = ColorLight.onSurfaceVariantLight,
        outline = ColorLight.outlineLight,
        outlineVariant = ColorLight.outlineVariantLight,
        scrim = ColorLight.scrimLight,
        inverseSurface = ColorLight.inverseSurfaceLight,
        inverseOnSurface = ColorLight.inverseOnSurfaceLight,
        inversePrimary = ColorLight.inversePrimaryLight,
        surfaceDim = ColorLight.surfaceDimLight,
        surfaceBright = ColorLight.surfaceBrightLight,
        surfaceContainerLowest = ColorLight.surfaceContainerLowestLight,
        surfaceContainerLow = ColorLight.surfaceContainerLowLight,
        surfaceContainer = ColorLight.surfaceContainerLight,
        surfaceContainerHigh = ColorLight.surfaceContainerHighLight,
        surfaceContainerHighest = ColorLight.surfaceContainerHighestLight,
    )

val darkScheme =
    darkColorScheme(
        primary = ColorDark.primaryDark,
        onPrimary = ColorDark.onPrimaryDark,
        primaryContainer = ColorDark.primaryContainerDark,
        onPrimaryContainer = ColorDark.onPrimaryContainerDark,
        secondary = ColorDark.secondaryDark,
        onSecondary = ColorDark.onSecondaryDark,
        secondaryContainer = ColorDark.secondaryContainerDark,
        onSecondaryContainer = ColorDark.onSecondaryContainerDark,
        tertiary = ColorDark.tertiaryDark,
        onTertiary = ColorDark.onTertiaryDark,
        tertiaryContainer = ColorDark.tertiaryContainerDark,
        onTertiaryContainer = ColorDark.onTertiaryContainerDark,
        error = ColorDark.errorDark,
        onError = ColorDark.onErrorDark,
        errorContainer = ColorDark.errorContainerDark,
        onErrorContainer = ColorDark.onErrorContainerDark,
        background = ColorDark.backgroundDark,
        onBackground = ColorDark.onBackgroundDark,
        surface = ColorDark.surfaceDark,
        onSurface = ColorDark.onSurfaceDark,
        surfaceVariant = ColorDark.surfaceVariantDark,
        onSurfaceVariant = ColorDark.onSurfaceVariantDark,
        outline = ColorDark.outlineDark,
        outlineVariant = ColorDark.outlineVariantDark,
        scrim = ColorDark.scrimDark,
        inverseSurface = ColorDark.inverseSurfaceDark,
        inverseOnSurface = ColorDark.inverseOnSurfaceDark,
        inversePrimary = ColorDark.inversePrimaryDark,
        surfaceDim = ColorDark.surfaceDimDark,
        surfaceBright = ColorDark.surfaceBrightDark,
        surfaceContainerLowest = ColorDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorDark.surfaceContainerLowDark,
        surfaceContainer = ColorDark.surfaceContainerDark,
        surfaceContainerHigh = ColorDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorDark.surfaceContainerHighestDark,
    )

val purpleLightScheme =
    lightColorScheme(
        primary = ColorPurpleLight.primaryLight,
        onPrimary = ColorPurpleLight.onPrimaryLight,
        primaryContainer = ColorPurpleLight.primaryContainerLight,
        onPrimaryContainer = ColorPurpleLight.onPrimaryContainerLight,
        secondary = ColorPurpleLight.secondaryLight,
        onSecondary = ColorPurpleLight.onSecondaryLight,
        secondaryContainer = ColorPurpleLight.secondaryContainerLight,
        onSecondaryContainer = ColorPurpleLight.onSecondaryContainerLight,
        tertiary = ColorPurpleLight.tertiaryLight,
        onTertiary = ColorPurpleLight.onTertiaryLight,
        tertiaryContainer = ColorPurpleLight.tertiaryContainerLight,
        onTertiaryContainer = ColorPurpleLight.onTertiaryContainerLight,
        error = ColorPurpleLight.errorLight,
        onError = ColorPurpleLight.onErrorLight,
        errorContainer = ColorPurpleLight.errorContainerLight,
        onErrorContainer = ColorPurpleLight.onErrorContainerLight,
        background = ColorPurpleLight.backgroundLight,
        onBackground = ColorPurpleLight.onBackgroundLight,
        surface = ColorPurpleLight.surfaceLight,
        onSurface = ColorPurpleLight.onSurfaceLight,
        surfaceVariant = ColorPurpleLight.surfaceVariantLight,
        onSurfaceVariant = ColorPurpleLight.onSurfaceVariantLight,
        outline = ColorPurpleLight.outlineLight,
        outlineVariant = ColorPurpleLight.outlineVariantLight,
        scrim = ColorPurpleLight.scrimLight,
        inverseSurface = ColorPurpleLight.inverseSurfaceLight,
        inverseOnSurface = ColorPurpleLight.inverseOnSurfaceLight,
        inversePrimary = ColorPurpleLight.inversePrimaryLight,
        surfaceDim = ColorPurpleLight.surfaceDimLight,
        surfaceBright = ColorPurpleLight.surfaceBrightLight,
        surfaceContainerLowest = ColorPurpleLight.surfaceContainerLowestLight,
        surfaceContainerLow = ColorPurpleLight.surfaceContainerLowLight,
        surfaceContainer = ColorPurpleLight.surfaceContainerLight,
        surfaceContainerHigh = ColorPurpleLight.surfaceContainerHighLight,
        surfaceContainerHighest = ColorPurpleLight.surfaceContainerHighestLight,
    )

val purpleDarkScheme =
    darkColorScheme(
        primary = ColorPurpleDark.primaryDark,
        onPrimary = ColorPurpleDark.onPrimaryDark,
        primaryContainer = ColorPurpleDark.primaryContainerDark,
        onPrimaryContainer = ColorPurpleDark.onPrimaryContainerDark,
        secondary = ColorPurpleDark.secondaryDark,
        onSecondary = ColorPurpleDark.onSecondaryDark,
        secondaryContainer = ColorPurpleDark.secondaryContainerDark,
        onSecondaryContainer = ColorPurpleDark.onSecondaryContainerDark,
        tertiary = ColorPurpleDark.tertiaryDark,
        onTertiary = ColorPurpleDark.onTertiaryDark,
        tertiaryContainer = ColorPurpleDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPurpleDark.onTertiaryContainerDark,
        error = ColorPurpleDark.errorDark,
        onError = ColorPurpleDark.onErrorDark,
        errorContainer = ColorPurpleDark.errorContainerDark,
        onErrorContainer = ColorPurpleDark.onErrorContainerDark,
        background = ColorPurpleDark.backgroundDark,
        onBackground = ColorPurpleDark.onBackgroundDark,
        surface = ColorPurpleDark.surfaceDark,
        onSurface = ColorPurpleDark.onSurfaceDark,
        surfaceVariant = ColorPurpleDark.surfaceVariantDark,
        onSurfaceVariant = ColorPurpleDark.onSurfaceVariantDark,
        outline = ColorPurpleDark.outlineDark,
        outlineVariant = ColorPurpleDark.outlineVariantDark,
        scrim = ColorPurpleDark.scrimDark,
        inverseSurface = ColorPurpleDark.inverseSurfaceDark,
        inverseOnSurface = ColorPurpleDark.inverseOnSurfaceDark,
        inversePrimary = ColorPurpleDark.inversePrimaryDark,
        surfaceDim = ColorPurpleDark.surfaceDimDark,
        surfaceBright = ColorPurpleDark.surfaceBrightDark,
        surfaceContainerLowest = ColorPurpleDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorPurpleDark.surfaceContainerLowDark,
        surfaceContainer = ColorPurpleDark.surfaceContainerDark,
        surfaceContainerHigh = ColorPurpleDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorPurpleDark.surfaceContainerHighestDark,
    )

val pinkLightScheme =
    lightColorScheme(
        primary = ColorPinkLight.primaryLight,
        onPrimary = ColorPinkLight.onPrimaryLight,
        primaryContainer = ColorPinkLight.primaryContainerLight,
        onPrimaryContainer = ColorPinkLight.onPrimaryContainerLight,
        secondary = ColorPinkLight.secondaryLight,
        onSecondary = ColorPinkLight.onSecondaryLight,
        secondaryContainer = ColorPinkLight.secondaryContainerLight,
        onSecondaryContainer = ColorPinkLight.onSecondaryContainerLight,
        tertiary = ColorPinkLight.tertiaryLight,
        onTertiary = ColorPinkLight.onTertiaryLight,
        tertiaryContainer = ColorPinkLight.tertiaryContainerLight,
        onTertiaryContainer = ColorPinkLight.onTertiaryContainerLight,
        error = ColorPinkLight.errorLight,
        onError = ColorPinkLight.onErrorLight,
        errorContainer = ColorPinkLight.errorContainerLight,
        onErrorContainer = ColorPinkLight.onErrorContainerLight,
        background = ColorPinkLight.backgroundLight,
        onBackground = ColorPinkLight.onBackgroundLight,
        surface = ColorPinkLight.surfaceLight,
        onSurface = ColorPinkLight.onSurfaceLight,
        surfaceVariant = ColorPinkLight.surfaceVariantLight,
        onSurfaceVariant = ColorPinkLight.onSurfaceVariantLight,
        outline = ColorPinkLight.outlineLight,
        outlineVariant = ColorPinkLight.outlineVariantLight,
        scrim = ColorPinkLight.scrimLight,
        inverseSurface = ColorPinkLight.inverseSurfaceLight,
        inverseOnSurface = ColorPinkLight.inverseOnSurfaceLight,
        inversePrimary = ColorPinkLight.inversePrimaryLight,
        surfaceDim = ColorPinkLight.surfaceDimLight,
        surfaceBright = ColorPinkLight.surfaceBrightLight,
        surfaceContainerLowest = ColorPinkLight.surfaceContainerLowestLight,
        surfaceContainerLow = ColorPinkLight.surfaceContainerLowLight,
        surfaceContainer = ColorPinkLight.surfaceContainerLight,
        surfaceContainerHigh = ColorPinkLight.surfaceContainerHighLight,
        surfaceContainerHighest = ColorPinkLight.surfaceContainerHighestLight,
    )

val pinkDarkScheme =
    darkColorScheme(
        primary = ColorPinkDark.primaryDark,
        onPrimary = ColorPinkDark.onPrimaryDark,
        primaryContainer = ColorPinkDark.primaryContainerDark,
        onPrimaryContainer = ColorPinkDark.onPrimaryContainerDark,
        secondary = ColorPinkDark.secondaryDark,
        onSecondary = ColorPinkDark.onSecondaryDark,
        secondaryContainer = ColorPinkDark.secondaryContainerDark,
        onSecondaryContainer = ColorPinkDark.onSecondaryContainerDark,
        tertiary = ColorPinkDark.tertiaryDark,
        onTertiary = ColorPinkDark.onTertiaryDark,
        tertiaryContainer = ColorPinkDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPinkDark.onTertiaryContainerDark,
        error = ColorPinkDark.errorDark,
        onError = ColorPinkDark.onErrorDark,
        errorContainer = ColorPinkDark.errorContainerDark,
        onErrorContainer = ColorPinkDark.onErrorContainerDark,
        background = ColorPinkDark.backgroundDark,
        onBackground = ColorPinkDark.onBackgroundDark,
        surface = ColorPinkDark.surfaceDark,
        onSurface = ColorPinkDark.onSurfaceDark,
        surfaceVariant = ColorPinkDark.surfaceVariantDark,
        onSurfaceVariant = ColorPinkDark.onSurfaceVariantDark,
        outline = ColorPinkDark.outlineDark,
        outlineVariant = ColorPinkDark.outlineVariantDark,
        scrim = ColorPinkDark.scrimDark,
        inverseSurface = ColorPinkDark.inverseSurfaceDark,
        inverseOnSurface = ColorPinkDark.inverseOnSurfaceDark,
        inversePrimary = ColorPinkDark.inversePrimaryDark,
        surfaceDim = ColorPinkDark.surfaceDimDark,
        surfaceBright = ColorPinkDark.surfaceBrightDark,
        surfaceContainerLowest = ColorPinkDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorPinkDark.surfaceContainerLowDark,
        surfaceContainer = ColorPinkDark.surfaceContainerDark,
        surfaceContainerHigh = ColorPinkDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorPinkDark.surfaceContainerHighestDark,
    )
