package com.vdc.tv.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.tv.material3.darkColorScheme as darkColorSchemeTv
import com.vdc.tv.core.presentation.theme.ColorDark
import com.vdc.tv.core.presentation.theme.ColorPinkDark
import com.vdc.tv.core.presentation.theme.ColorPurpleDark

val darkScheme =
    darkColorScheme(
        primary = ColorDark.primaryDark,
        onPrimary = ColorDark.onPrimaryDark,
        primaryContainer = ColorDark.primaryContainerDark,
        onPrimaryContainer = ColorDark.onPrimaryContainerDark,
        secondary = ColorDark.secondaryDark,
        onSecondary = ColorDark.onSecondaryDark,
        secondaryContainer = ColorDark.secondaryContainerDark,
        onSecondaryContainer = ColorDark.onSecondaryContainerDark,
        tertiary = ColorDark.tertiaryDark,
        onTertiary = ColorDark.onTertiaryDark,
        tertiaryContainer = ColorDark.tertiaryContainerDark,
        onTertiaryContainer = ColorDark.onTertiaryContainerDark,
        error = ColorDark.errorDark,
        onError = ColorDark.onErrorDark,
        errorContainer = ColorDark.errorContainerDark,
        onErrorContainer = ColorDark.onErrorContainerDark,
        background = ColorDark.backgroundDark,
        onBackground = ColorDark.onBackgroundDark,
        surface = ColorDark.surfaceDark,
        onSurface = ColorDark.onSurfaceDark,
        surfaceVariant = ColorDark.surfaceVariantDark,
        onSurfaceVariant = ColorDark.onSurfaceVariantDark,
        outline = ColorDark.outlineDark,
        outlineVariant = ColorDark.outlineVariantDark,
        scrim = ColorDark.scrimDark,
        inverseSurface = ColorDark.inverseSurfaceDark,
        inverseOnSurface = ColorDark.inverseOnSurfaceDark,
        inversePrimary = ColorDark.inversePrimaryDark,
        surfaceDim = ColorDark.surfaceDimDark,
        surfaceBright = ColorDark.surfaceBrightDark,
        surfaceContainerLowest = ColorDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorDark.surfaceContainerLowDark,
        surfaceContainer = ColorDark.surfaceContainerDark,
        surfaceContainerHigh = ColorDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorDark.surfaceContainerHighestDark,
    )

val darkSchemeTv =
    darkColorSchemeTv(
        primary = ColorDark.primaryDark,
        onPrimary = ColorDark.onPrimaryDark,
        primaryContainer = ColorDark.primaryContainerDark,
        onPrimaryContainer = ColorDark.onPrimaryContainerDark,
        secondary = ColorDark.secondaryDark,
        onSecondary = ColorDark.onSecondaryDark,
        secondaryContainer = ColorDark.secondaryContainerDark,
        onSecondaryContainer = ColorDark.onSecondaryContainerDark,
        tertiary = ColorDark.tertiaryDark,
        onTertiary = ColorDark.onTertiaryDark,
        tertiaryContainer = ColorDark.tertiaryContainerDark,
        onTertiaryContainer = ColorDark.onTertiaryContainerDark,
        error = ColorDark.errorDark,
        onError = ColorDark.onErrorDark,
        errorContainer = ColorDark.errorContainerDark,
        onErrorContainer = ColorDark.onErrorContainerDark,
        background = ColorDark.backgroundDark,
        onBackground = ColorDark.onBackgroundDark,
        surface = ColorDark.surfaceDark,
        onSurface = ColorDark.onSurfaceDark,
        surfaceVariant = ColorDark.surfaceVariantDark,
        onSurfaceVariant = ColorDark.onSurfaceVariantDark,
        scrim = ColorDark.scrimDark,
        inverseSurface = ColorDark.inverseSurfaceDark,
        inverseOnSurface = ColorDark.inverseOnSurfaceDark,
        inversePrimary = ColorDark.inversePrimaryDark,
    )

val purpleDarkScheme =
    darkColorScheme(
        primary = ColorPurpleDark.primaryDark,
        onPrimary = ColorPurpleDark.onPrimaryDark,
        primaryContainer = ColorPurpleDark.primaryContainerDark,
        onPrimaryContainer = ColorPurpleDark.onPrimaryContainerDark,
        secondary = ColorPurpleDark.secondaryDark,
        onSecondary = ColorPurpleDark.onSecondaryDark,
        secondaryContainer = ColorPurpleDark.secondaryContainerDark,
        onSecondaryContainer = ColorPurpleDark.onSecondaryContainerDark,
        tertiary = ColorPurpleDark.tertiaryDark,
        onTertiary = ColorPurpleDark.onTertiaryDark,
        tertiaryContainer = ColorPurpleDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPurpleDark.onTertiaryContainerDark,
        error = ColorPurpleDark.errorDark,
        onError = ColorPurpleDark.onErrorDark,
        errorContainer = ColorPurpleDark.errorContainerDark,
        onErrorContainer = ColorPurpleDark.onErrorContainerDark,
        background = ColorPurpleDark.backgroundDark,
        onBackground = ColorPurpleDark.onBackgroundDark,
        surface = ColorPurpleDark.surfaceDark,
        onSurface = ColorPurpleDark.onSurfaceDark,
        surfaceVariant = ColorPurpleDark.surfaceVariantDark,
        onSurfaceVariant = ColorPurpleDark.onSurfaceVariantDark,
        outline = ColorPurpleDark.outlineDark,
        outlineVariant = ColorPurpleDark.outlineVariantDark,
        scrim = ColorPurpleDark.scrimDark,
        inverseSurface = ColorPurpleDark.inverseSurfaceDark,
        inverseOnSurface = ColorPurpleDark.inverseOnSurfaceDark,
        inversePrimary = ColorPurpleDark.inversePrimaryDark,
        surfaceDim = ColorPurpleDark.surfaceDimDark,
        surfaceBright = ColorPurpleDark.surfaceBrightDark,
        surfaceContainerLowest = ColorPurpleDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorPurpleDark.surfaceContainerLowDark,
        surfaceContainer = ColorPurpleDark.surfaceContainerDark,
        surfaceContainerHigh = ColorPurpleDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorPurpleDark.surfaceContainerHighestDark,
    )

val purpleDarkSchemeTv =
    darkColorSchemeTv(
        primary = ColorPurpleDark.primaryDark,
        onPrimary = ColorPurpleDark.onPrimaryDark,
        primaryContainer = ColorPurpleDark.primaryContainerDark,
        onPrimaryContainer = ColorPurpleDark.onPrimaryContainerDark,
        secondary = ColorPurpleDark.secondaryDark,
        onSecondary = ColorPurpleDark.onSecondaryDark,
        secondaryContainer = ColorPurpleDark.secondaryContainerDark,
        onSecondaryContainer = ColorPurpleDark.onSecondaryContainerDark,
        tertiary = ColorPurpleDark.tertiaryDark,
        onTertiary = ColorPurpleDark.onTertiaryDark,
        tertiaryContainer = ColorPurpleDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPurpleDark.onTertiaryContainerDark,
        error = ColorPurpleDark.errorDark,
        onError = ColorPurpleDark.onErrorDark,
        errorContainer = ColorPurpleDark.errorContainerDark,
        onErrorContainer = ColorPurpleDark.onErrorContainerDark,
        background = ColorPurpleDark.backgroundDark,
        onBackground = ColorPurpleDark.onBackgroundDark,
        surface = ColorPurpleDark.surfaceDark,
        onSurface = ColorPurpleDark.onSurfaceDark,
        surfaceVariant = ColorPurpleDark.surfaceVariantDark,
        onSurfaceVariant = ColorPurpleDark.onSurfaceVariantDark,
        scrim = ColorPurpleDark.scrimDark,
        inverseSurface = ColorPurpleDark.inverseSurfaceDark,
        inverseOnSurface = ColorPurpleDark.inverseOnSurfaceDark,
        inversePrimary = ColorPurpleDark.inversePrimaryDark,
    )

val pinkDarkScheme =
    darkColorScheme(
        primary = ColorPinkDark.primaryDark,
        onPrimary = ColorPinkDark.onPrimaryDark,
        primaryContainer = ColorPinkDark.primaryContainerDark,
        onPrimaryContainer = ColorPinkDark.onPrimaryContainerDark,
        secondary = ColorPinkDark.secondaryDark,
        onSecondary = ColorPinkDark.onSecondaryDark,
        secondaryContainer = ColorPinkDark.secondaryContainerDark,
        onSecondaryContainer = ColorPinkDark.onSecondaryContainerDark,
        tertiary = ColorPinkDark.tertiaryDark,
        onTertiary = ColorPinkDark.onTertiaryDark,
        tertiaryContainer = ColorPinkDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPinkDark.onTertiaryContainerDark,
        error = ColorPinkDark.errorDark,
        onError = ColorPinkDark.onErrorDark,
        errorContainer = ColorPinkDark.errorContainerDark,
        onErrorContainer = ColorPinkDark.onErrorContainerDark,
        background = ColorPinkDark.backgroundDark,
        onBackground = ColorPinkDark.onBackgroundDark,
        surface = ColorPinkDark.surfaceDark,
        onSurface = ColorPinkDark.onSurfaceDark,
        surfaceVariant = ColorPinkDark.surfaceVariantDark,
        onSurfaceVariant = ColorPinkDark.onSurfaceVariantDark,
        outline = ColorPinkDark.outlineDark,
        outlineVariant = ColorPinkDark.outlineVariantDark,
        scrim = ColorPinkDark.scrimDark,
        inverseSurface = ColorPinkDark.inverseSurfaceDark,
        inverseOnSurface = ColorPinkDark.inverseOnSurfaceDark,
        inversePrimary = ColorPinkDark.inversePrimaryDark,
        surfaceDim = ColorPinkDark.surfaceDimDark,
        surfaceBright = ColorPinkDark.surfaceBrightDark,
        surfaceContainerLowest = ColorPinkDark.surfaceContainerLowestDark,
        surfaceContainerLow = ColorPinkDark.surfaceContainerLowDark,
        surfaceContainer = ColorPinkDark.surfaceContainerDark,
        surfaceContainerHigh = ColorPinkDark.surfaceContainerHighDark,
        surfaceContainerHighest = ColorPinkDark.surfaceContainerHighestDark,
    )

val pinkDarkSchemeTv =
    darkColorSchemeTv(
        primary = ColorPinkDark.primaryDark,
        onPrimary = ColorPinkDark.onPrimaryDark,
        primaryContainer = ColorPinkDark.primaryContainerDark,
        onPrimaryContainer = ColorPinkDark.onPrimaryContainerDark,
        secondary = ColorPinkDark.secondaryDark,
        onSecondary = ColorPinkDark.onSecondaryDark,
        secondaryContainer = ColorPinkDark.secondaryContainerDark,
        onSecondaryContainer = ColorPinkDark.onSecondaryContainerDark,
        tertiary = ColorPinkDark.tertiaryDark,
        onTertiary = ColorPinkDark.onTertiaryDark,
        tertiaryContainer = ColorPinkDark.tertiaryContainerDark,
        onTertiaryContainer = ColorPinkDark.onTertiaryContainerDark,
        error = ColorPinkDark.errorDark,
        onError = ColorPinkDark.onErrorDark,
        errorContainer = ColorPinkDark.errorContainerDark,
        onErrorContainer = ColorPinkDark.onErrorContainerDark,
        background = ColorPinkDark.backgroundDark,
        onBackground = ColorPinkDark.onBackgroundDark,
        surface = ColorPinkDark.surfaceDark,
        onSurface = ColorPinkDark.onSurfaceDark,
        surfaceVariant = ColorPinkDark.surfaceVariantDark,
        onSurfaceVariant = ColorPinkDark.onSurfaceVariantDark,
        scrim = ColorPinkDark.scrimDark,
        inverseSurface = ColorPinkDark.inverseSurfaceDark,
        inverseOnSurface = ColorPinkDark.inverseOnSurfaceDark,
        inversePrimary = ColorPinkDark.inversePrimaryDark,
    )
